version: "3"
name: "simple-discord"

services:
  migrate:
    container_name: migrate
    build:
      context: .
      dockerfile: ./migrate/.docker/Dockerfile
    command: ["npm", "run", "migrate:run"]

  app:
    container_name: app
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./app/.docker/Dockerfile
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: [ "npm", "run", "start" ]
